
import { Lead, Property } from './types';

export const INITIAL_LEADS: Lead[] = [
  {
    id: '1',
    name: 'Vikram Malhotra',
    email: 'v.malhotra@tech-india.com',
    phone: '+91 98765 43210',
    location: 'Bangalore / London',
    citizenship: 'NRI (UK Resident)',
    netWorth: '$50M+',
    investmentBudget: '$5M - $10M',
    status: 'Negotiation',
    dealValue: 8500000,
    probability: 75,
    preferredPropertyTypes: ['Penthouse'],
    lastInteraction: '2023-10-24',
    notes: 'Very close to closing on the Azure Penthouse. Needs final confirmation on NRI tax compliance.',
  },
  {
    id: '2',
    name: 'Sarah Thompson',
    email: 's.thompson@global-invest.com',
    phone: '+1 212 555 0198',
    location: 'New York',
    citizenship: 'US Citizen (HNI)',
    netWorth: '$120M',
    investmentBudget: '$15M - $25M',
    status: 'Site Visit',
    probability: 40,
    preferredPropertyTypes: ['Heritage Estate'],
    lastInteraction: '2023-10-22',
    notes: 'Flying in for a private viewing of the Lutyens estate next month.',
  },
  {
    id: '3',
    name: 'Ananya Iyer',
    email: 'ananya@iyer-legal.com',
    phone: '+65 8822 4411',
    location: 'Singapore',
    citizenship: 'NRI (Singapore Resident)',
    netWorth: '$35M',
    investmentBudget: '$3M - $7M',
    status: 'Prospect',
    probability: 10,
    preferredPropertyTypes: ['Duplex Penthouse'],
    lastInteraction: '2023-10-25',
    notes: 'Initial inquiry via private referral. Interested in Worli area.',
  },
  {
    id: '4',
    name: 'Rajesh Khanna',
    email: 'khanna@dubai-capital.ae',
    phone: '+971 50 123 4567',
    location: 'Dubai',
    citizenship: 'NRI (UAE Resident)',
    netWorth: '$200M+',
    investmentBudget: '$20M+',
    status: 'Closed',
    dealValue: 22000000,
    probability: 100,
    preferredPropertyTypes: ['Ultra-Mansion'],
    lastInteraction: '2023-09-15',
    notes: 'Purchase of Heritage Oaks completed. Retained for property management.',
  }
];

export const LUXURY_PROPERTIES: Property[] = [
  {
    id: 'p1',
    title: 'The Azure Penthouse',
    location: 'Worli, Mumbai',
    price: '$8,500,000',
    numericPrice: 8500000,
    sqft: 12500,
    beds: 5,
    baths: 6,
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=2070&auto=format&fit=crop',
    amenities: ['Private Infinity Pool', 'Wine Cellar', '24/7 Concierge'],
    description: 'A masterpiece of modern living overlooking the Arabian Sea.',
  },
  {
    id: 'p2',
    title: 'Heritage Oaks Estate',
    location: 'Lutyens, Delhi',
    price: '$22,000,000',
    numericPrice: 22000000,
    sqft: 25000,
    beds: 8,
    baths: 10,
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=2070&auto=format&fit=crop',
    amenities: ['Helipad', 'Cricket Pitch', '10-Car Garage', 'Staff Quarters'],
    description: 'The pinnacle of legacy real estate in the heart of the capital.',
  },
  {
    id: 'p3',
    title: 'Villa Serenity',
    location: 'North Goa',
    price: '$4,200,000',
    numericPrice: 42000000,
    sqft: 8500,
    beds: 4,
    baths: 5,
    image: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=2071&auto=format&fit=crop',
    amenities: ['Private Beach Access', 'Smart Home System', 'Zen Garden'],
    description: 'Bespoke coastal living for those who seek absolute privacy.',
  }
];
